SELECT * FROM tabela 
	WHERE	campoA = 1 
		OR	campoB = "texto" 
		AND	campoC <> 2.12 
		OR	campoD > "texto2" 
		OR	campoE < 3 
		OR	tabela.'campoF' <= 7 
		OR	'tabela'.campoG >= 6
		AND	'campoH' = 25/10/2014;